import { createHash, randomBytes } from "node:crypto";
import { lstat, mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { Database } from "bun:sqlite";
import { readPreparedE2ERun } from "./e2e-network";

const [action, rootArgument, sourceName, destinationName, relativePath] = Bun.argv.slice(2);
if (
  !["transfer", "delete"].includes(action ?? "") ||
  !rootArgument ||
  !sourceName ||
  !destinationName ||
  !relativePath
) {
  usage();
}

const allowedProofs = new Set([
  "E2E Sync Proof.md",
  "Reverse Sync Proof.md",
  "Deletion Sync Proof.md",
]);
if (!allowedProofs.has(relativePath)) {
  throw new Error(`Unsupported E2E proof path: ${relativePath}`);
}
if (
  !["client-a", "client-b"].includes(sourceName) ||
  !["client-a", "client-b"].includes(destinationName) ||
  sourceName === destinationName
) {
  throw new Error("E2E transfer must use two distinct prepared clients");
}

const e2eRoot = resolve(import.meta.dir, "../.data/e2e");
const root = (await readPreparedE2ERun(rootArgument)).root;
const source = join(root, sourceName, "vault", relativePath);
const destination = join(root, destinationName, "vault", relativePath);
await assertNoSymlinkSegments(source);
await assertNoSymlinkSegments(destination);

const slug = relativePath.replace(/\.md$/u, "").toLocaleLowerCase().replaceAll(" ", "-");
const output = join(root, "observations", `${action}-${slug}.json`);
if (await exists(output)) throw new Error(`Refusing to overwrite E2E observation: ${output}`);

if (action === "transfer") {
  if (await exists(source) || await exists(destination)) {
    throw new Error(`Transfer proof must not already exist: ${relativePath}`);
  }
  const before = databaseSnapshot(join(root, "server.sqlite"));
  const marker = randomBytes(24).toString("base64url");
  const contents = Buffer.from(
    `# ${relativePath.replace(/\.md$/u, "")}\n\n` +
      `Generated by the Blackglass exact-artifact E2E observer.\n\n` +
      `Marker: ${marker}\n`,
  );
  await writeFile(source, contents, { flag: "wx", mode: 0o600 });
  const sourceCreatedAt = new Date().toISOString();
  const deadline = Date.now() + 120_000;
  let after: DatabaseSnapshot | undefined;
  while (Date.now() < deadline) {
    const candidate = await readIfExists(destination);
    const current = databaseSnapshot(join(root, "server.sqlite"));
    if (
      candidate?.equals(contents) &&
      current.revisions > before.revisions &&
      current.maxUid > before.maxUid &&
      current.vaultVersion > before.vaultVersion
    ) {
      after = current;
      break;
    }
    await Bun.sleep(100);
  }
  if (!after) {
    throw new Error(`Timed out waiting for background Sync transfer: ${relativePath}`);
  }
  await writeObservation(output, {
    schemaVersion: 1,
    action,
    observedAt: new Date().toISOString(),
    sourceClient: sourceName,
    destinationClient: destinationName,
    relativePath,
    sourceCreatedAt,
    bytes: contents.byteLength,
    sha256: sha256(contents),
    markerSha256: sha256(Buffer.from(marker)),
    databaseBefore: before,
    databaseAfter: after,
  });
} else {
  const sourceBytes = await readFile(source);
  const destinationBytes = await readFile(destination);
  if (!sourceBytes.equals(destinationBytes)) {
    throw new Error(`Cannot observe deletion before the two clients converge: ${relativePath}`);
  }
  const before = databaseSnapshot(join(root, "server.sqlite"));
  await unlink(source);
  const sourceDeletedAt = new Date().toISOString();
  const deadline = Date.now() + 120_000;
  let after: DatabaseSnapshot | undefined;
  while (Date.now() < deadline) {
    const current = databaseSnapshot(join(root, "server.sqlite"));
    if (
      !(await exists(destination)) &&
      current.revisions > before.revisions &&
      current.maxUid > before.maxUid &&
      current.vaultVersion > before.vaultVersion
    ) {
      after = current;
      break;
    }
    await Bun.sleep(100);
  }
  if (!after) {
    throw new Error(`Timed out waiting for background Sync deletion: ${relativePath}`);
  }
  await writeObservation(output, {
    schemaVersion: 1,
    action,
    observedAt: new Date().toISOString(),
    sourceClient: sourceName,
    destinationClient: destinationName,
    relativePath,
    sourceDeletedAt,
    bytes: sourceBytes.byteLength,
    sha256: sha256(sourceBytes),
    databaseBefore: before,
    databaseAfter: after,
  });
}

console.log(JSON.stringify(JSON.parse(await readFile(output, "utf8")), null, 2));

type DatabaseSnapshot = {
  revisions: number;
  maxUid: number;
  vaultVersion: number;
  vaultSize: number;
};

function databaseSnapshot(path: string): DatabaseSnapshot {
  const database = new Database(path, { readonly: true, strict: true });
  try {
    const revision = database
      .query<{ revisions: number; maxUid: number }, []>(
        "SELECT COUNT(*) AS revisions, COALESCE(MAX(uid), 0) AS maxUid FROM revisions",
      )
      .get();
    const vault = database
      .query<{ version: number; size: number }, []>(
        "SELECT version, size FROM vaults ORDER BY created LIMIT 1",
      )
      .get();
    if (!revision || !vault) throw new Error("E2E database has no remote vault");
    return {
      revisions: revision.revisions,
      maxUid: revision.maxUid,
      vaultVersion: vault.version,
      vaultSize: vault.size,
    };
  } finally {
    database.close();
  }
}

async function writeObservation(path: string, value: unknown): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.next`;
  await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, {
    flag: "wx",
    mode: 0o600,
  });
  await rename(temporary, path);
}

async function readIfExists(path: string): Promise<Buffer | undefined> {
  try {
    return await readFile(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

async function exists(path: string): Promise<boolean> {
  return (await readIfExists(path)) !== undefined;
}

async function assertNoSymlinkSegments(path: string): Promise<void> {
  const relativePath = relative(e2eRoot, path);
  let current = e2eRoot;
  for (const segment of relativePath.split("/").filter(Boolean)) {
    current = join(current, segment);
    try {
      if ((await lstat(current)).isSymbolicLink()) {
        throw new Error(`E2E proof path must not traverse a symbolic link: ${current}`);
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      throw error;
    }
  }
}

function sha256(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function usage(): never {
  console.error(
    "Usage: bun run tools/observe-e2e.ts <transfer|delete> <run-directory> " +
      "<source-client> <destination-client> <proof.md>",
  );
  process.exit(2);
}
